### ISSUE TITLE
New Gem Release

### ISSUE THREAD

**Issue by markrickert** [tkadauke/motion-i18n#10]
Can we get one soon? Last release was in 2013 and there are a few new things that i'd like to use without having to reference git in my Gemfile... notably multiple substitution of variables.

Thanks!

**Comment by tkadauke** [comment]
Done (version 0.0.4)

**Comment by markrickert** [comment]
Might want to take a look at my PR and maybe release 0.0.5? Sorry for the timing on this issue and that PR.

**Comment by tkadauke** [comment]
Done (version 0.0.5) :)

**Comment by markrickert** [comment]
Sweet! Thanks man!
